NAME: 配置信息
CONFIG:
    Cookies: #cook信息
        LoginCookies: {"pos_entry_number":"1003935039186461",
               "pos_entry_actualcard":"1003935039186461",
               "pos_bid":"2048695606",
               "pos_mid":"1234871385",
               "pos_sid":"1512995661",
               "pos_sign":"369240630d5e17a24bf7e5a70f073465"}


RUNING: #case执行配置
    DESCPTION: N不执行，Y执行
    CONSUME: #消费模块
        Flag: {"testCase1":{"Flag":"N","desc":"实体卡开卡"},
        "testCase5":{"Flag":"Y","desc":"实体卡绑卡"}}

    CHARGE: #储值模块
        Flag: {"testCase1":"Y","testCase2":"Y"}
    CREDIT: #积分换礼模块
        Flag: {"testCase1":"Y","testCase2":"Y"}